# Generated by Django 2.2.13 on 2021-10-01 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut_adm', models.TextField(primary_key=True, serialize=False)),
                ('pass_field', models.TextField(db_column='pass')),
                ('nombre_adm', models.TextField()),
                ('apat_adm', models.TextField()),
                ('amat_adm', models.TextField()),
                ('email_admin', models.TextField()),
                ('fono_admin', models.BigIntegerField()),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id_cajero', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_cajero', models.TextField()),
            ],
            options={
                'db_table': 'cajero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.TextField(primary_key=True, serialize=False)),
                ('nombre_cli', models.TextField()),
                ('apaterno_cli', models.TextField()),
                ('amaterno_cli', models.TextField()),
                ('fono_cli', models.BigIntegerField()),
                ('email_cli', models.TextField()),
                ('saldo_cli', models.BigIntegerField()),
                ('pass_field', models.TextField(db_column='pass')),
                ('direccion_cliente', models.TextField()),
                ('convenio', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cli', models.TextField()),
                ('nom_cli', models.TextField()),
                ('nom_emp', models.TextField()),
                ('rut_emp', models.TextField()),
                ('tipo_suscrip', models.TextField()),
            ],
            options={
                'db_table': 'convenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleInsumos',
            fields=[
                ('id_det_ins', models.BigIntegerField(primary_key=True, serialize=False)),
                ('desc_det_ins', models.TextField()),
                ('valor_ing', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalle_insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rut_emp', models.TextField(primary_key=True, serialize=False)),
                ('nom_emp', models.TextField()),
                ('nom_gerente', models.TextField()),
                ('cant_trabajadores', models.BigIntegerField()),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncCocina',
            fields=[
                ('id_enc_cocina', models.AutoField(primary_key=True, serialize=False)),
                ('nom_enc_cocina', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('exp_laboral', models.IntegerField()),
                ('email_enc_cocina', models.EmailField(max_length=254)),
                ('contraseña1', models.CharField(max_length=100)),
                ('contraseña2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'enc_cocina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncConvenio',
            fields=[
                ('id_enc_conv', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_enc_conv', models.TextField()),
                ('nom_enc_conv', models.TextField()),
                ('ap_enc_conv', models.TextField()),
                ('email_enc_conv', models.TextField()),
            ],
            options={
                'db_table': 'enc_convenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.BigIntegerField()),
                ('id_plato', models.BigIntegerField()),
                ('fec_pedido', models.TextField()),
                ('total_pedido', models.BigIntegerField()),
                ('nom_plato', models.TextField()),
                ('nom_ing', models.TextField()),
                ('valor_ing', models.BigIntegerField()),
            ],
            options={
                'db_table': 'informes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ing', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_ing', models.TextField()),
                ('desc_ing', models.TextField()),
                ('tipo_ing', models.TextField()),
            ],
            options={
                'db_table': 'ingrediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_pago', models.TextField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.TextField()),
                ('fecha_pedido', models.TextField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_plato', models.TextField()),
                ('valor_plato', models.BigIntegerField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'plato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preparacin',
            fields=[
                ('id_prepa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('desc_preparacion', models.TextField()),
                ('lista_ing', models.TextField()),
            ],
            options={
                'db_table': 'preparación',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rol_local', models.TextField()),
                ('nom_proveedor', models.TextField()),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id_repartidor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_repartidor', models.TextField()),
                ('apellido_repartidor', models.TextField()),
                ('patente_veh', models.TextField()),
            ],
            options={
                'db_table': 'repartidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id_restaurante', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_rest', models.TextField()),
                ('direccion_rest', models.TextField()),
                ('comuna_rest', models.TextField()),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suscripcin',
            fields=[
                ('id_suscrip', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_suscrip', models.TextField()),
                ('desc_suscrip', models.TextField()),
            ],
            options={
                'db_table': 'suscripción',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('tipo_plato', models.TextField()),
                ('estilo_comida', models.TextField()),
                ('restaurant_id_restaurante', models.ForeignKey(db_column='restaurant_id_restaurante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='OrderFood.Restaurant')),
            ],
            options={
                'db_table': 'carta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetPago',
            fields=[
                ('precio_unidad', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
                ('direccion_entrega', models.TextField()),
                ('pago_id_pago', models.ForeignKey(db_column='pago_id_pago', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='OrderFood.Pago')),
            ],
            options={
                'db_table': 'det_pago',
                'managed': False,
            },
        ),
    ]
