# Generated by Django 2.2.13 on 2021-10-01 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enccocina',
            options={},
        ),
    ]
