# Generated by Django 2.2.13 on 2021-10-01 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0002_auto_20211001_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encconvenio',
            options={},
        ),
    ]
