# Generated by Django 2.2.13 on 2021-10-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0003_auto_20211001_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='encconvenio',
            name='contraseña1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encconvenio',
            name='contraseña2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encconvenio',
            name='ap_enc_conv',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='encconvenio',
            name='email_enc_conv',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='encconvenio',
            name='id_enc_conv',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encconvenio',
            name='nom_enc_conv',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='encconvenio',
            name='rut_enc_conv',
            field=models.CharField(max_length=100),
        ),
    ]
